"""add transactions table

Revision ID: 89205e831994
Revises: db66e3225837
Create Date: 2025-04-17 16:12:24.842630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89205e831994'
down_revision = 'db66e3225837'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_type', sa.Enum('individual', 'legal', name='persontype'), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('transaction_type', sa.Enum('income', 'expense', name='transactiontype'), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('new', 'confirmed', 'processing', 'canceled', 'completed', 'deleted', 'refund', name='transactionstatus'), nullable=False),
    sa.Column('sender_bank', sa.String(), nullable=True),
    sa.Column('sender_account', sa.String(), nullable=True),
    sa.Column('recipient_bank', sa.String(), nullable=True),
    sa.Column('recipient_inn', sa.String(), nullable=False),
    sa.Column('recipient_account', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('recipient_phone', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
