"""create transactions table

Revision ID: db66e3225837
Revises: f61a24c81366
Create Date: 2025-04-17 16:10:10.814229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db66e3225837'
down_revision = 'f61a24c81366'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
